### ISSUE TITLE
How to set the parameters

### ISSUE THREAD

**Issue by whu-zhigao** [ogreen/GpuTriangleCounting#1]
Hi @ogreen ,
I try to run this project on Ubuntu 16.04 with CUDA 10.2, with gcc 7.5. I can compile the code, but there is a problem when I run the exec file. I assigned many kinds of values of the parameters, but I always got the following error, which puzzled me a lot.
Invalid threads per intersection(1,2,4,8,16,32).
More number of partitions than blocks!
Exiting..

Would you please let me know the detailed requirements of the following parameters?
PAR_FILENAME        1 (Required)
      PAR_BLOCKS          2 (Required)
      PAR_BLOCKSIZE       3 (' ' | 32,64,96,128,192,256,512,1024)
      PAR_THPERINTER      4 (' ' | 1,2,4,8,16,32)
      PAR_PARTITION       5 (' ' | < PAR_BLOCKS)

**Comment by ogreen** [comment]
Hey @pkuwalter , I would suggest looking at the code here:
https://github.com/rapidsai/cuhornet/blob/master/hornetsnest/test/TriangleTest2.cu

This is an improved triangle counting algorithm that does the "parameter selection" on the fly based on the sizes of the list. Each edge "gets" a different number of threads.

If you are looking for the papers describing the algorithm in more detail I suggest:

- J. Fox, O. Green, K. Gabert, X. An, D. Bader, “Fast and Adaptive List Intersections on the GPU” [LINK](https://www.researchgate.net/publication/327570751_Fast_and_Adaptive_List_Intersections_on_the_GPU)
- J. Fox, A. Tripathy, O. Green “Improving Scheduling for Irregular Applications with Logarithmic Radix Binning” [LINK](https://www.researchgate.net/publication/335723059_Improving_Scheduling_for_Irregular_Applications_with_Logarithmic_Radix_Binning)

**Comment by whu-zhigao** [comment]
thanks for your timely reply.
